#+TITLE:     Biomateriales poliméricos

#+STARTUP: beamer
#+SETUPFILE: config.org
#+OPTIONS: H:3
#+OPTIONS: ^:{}
#+OPTIONS: _:{}
#+PROPERTY: header-args :results output :exports both :session R:class :tangle yes :comments org

** Introducción 

*** Breve historia de los materiales poliméricos o polímeros 

**** Edad Antigua 

Los materiales poliméricos de origen natural se comenzaron a utilizar a partir del desarrollo de las primeras civilizaciones. Algunos de los más usados han sido la madera (desde 8000 a.C) para la construcción de viviendas, la seda (dese 3000 a.C.) para fabricar tejidos, o el almidón o fécula (desde 3500 a.C) —glúcido de reserva de la mayoría de los vegetales, compuesto por dos polímeros distintos de glucosa, la amilosa (en proporción del 25%) y la amilopectina (75%)— como adhesivo en materiales de construcción y para fines medicinales. 
  
**** Siglo XIX y principios del XX  
   - En el siglo XIX se desarollaron los primeros modelos sobre los materiales polímericos, representando su microestructura como un conjunto de cadenas moleculares largas. 
   - 1836: Charles Goodyear describe de manera científica el fenómeno de la vulcanización del caucho. El caucho o hule (hidrocarburo: C_{5}H_{8}) es una sustancia natural caracterizada por su insolubilidad en agua, su resistencia eléctrica y su elasticidad, que se encuentra en forma de suspensión coloidal en el látex. La vulcanización es un proceso mediante el cual se calienta el caucho natural en presencia de azufre, obteniéndose un material más duro e impermeable. Charles Goodyear denominó a este proceso de endurecimiento "vulcanización", en honor al dios romano del fuego, Vulcano. Recientemente, investigaciones arqueológicas de finales de 1980s revelaron la presencia de pelotas de caucho en un pueblo mesoamericano precolombino, por lo que podría haber sido una civilización pionera en el dedscubrimiento del fenómeno de la vulcanización.
   - 1909: Adolf von Baeyer sintetiza el primer polímero de origen no natural o sintético, la baquelita. Se sintetizó a partir de moléculas de fenol y formaldehído. La baquelita se utilizó en diversas industrias tecnológicas, como material de carcarsas para teléfonos y radios.
   - 1926: Hermann Staudinger (Premio Nobel de Química en 1953) acuña el término de macromolécula y sienta las bases científicas de la polimerización. Expone su hipótesis de que un polímero es una larga cadena de unidades pequeñas unidas por enlaces covalentes. 
   
**** Siglo XX
   - El campo de los materiales polímeros se desarrolló de forma exponencial en el periodo de entreguerras y durante Segunda Guerra mundial. Por ejemplo, se desarrollaron nuevos plásticos para aislarse de la detección de radares. Además se sintetizaron nuevos poliméricos como el Nylon (1930), el Polietileno (1933) y el Polietileno (1941)
   
   
*** Definición, estructura y composición química 

**** Microestructura  

***** Monómero(s) y unidad repetitiva 
   - Un polímero es una macromolécula orgánica relativamente grande (10^{4}- 10^{6} g/mol) compuesta por una combinación de múltiples unidades pequeñas que se repiten. A las pequeñas unidades que se repiten se les denomina "monómeros", y la unidad que se repite a lo largo de la cadena se llama "unidad estructural repetida". 
   
   
***** Composición química
   - La mayoría de los monómeros están compuestos por carbono, hidrógeno, oxígeno y nitrógeno. Unos pocos elementos adicionales pueden existir, tales como el floro, el cloro, el sulfuro, etc.
   
   
***** Mecanismo de polimerización
   - La síntesis de pollímeros se lleva a cabo en reactores, a menudo con la aplicación de calor y temperatura, para que de esta forma las unidades monoméricas se conecten unas con otras por medio de una reacción química. Al proceso químico de síntesis de polímeros se le denomina polimerización.
   - 
   
***** Configuración: isómeros, tacticida 

***** Conformación

Monómero(s) y unidad repetitiva
Configuración: isómeros, tacticidad
Conformación: 



**** Macroestructura

***** Peso molecular, ramificación

***** Enlaces (o no) entre moléculas

**** Aditivos  
Si se usan 


** Tipos 

   
** Propiedades  

** Aplicaciones 


** Footnotes

[fn:2]https://lifewatch.inbo.be/blog/files/bird_tracking.zip 

[fn:1] https://lifewatch.inbo.be/blog/posts/bird-tracking-data-published.html
